apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-principal
  annotations:
    kubernetes.io/ingress.class: "nginx"
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  rules:
  - host: poliformas.com.gt
    http:
      paths:
      - path: /
        backend:
          serviceName: service-vuejs
          servicePort: 80
  - host: backend.poliformas.com.gt
    http:
      paths:
      - path: /api/vendedores
        backend:
          serviceName: service-nodejs-vendedores
          servicePort: 5000
      - path: /api/movimientos
        backend:
          serviceName: service-nodejs-movimientos
          servicePort: 5000
      - path: /api/marcas
        backend:
          serviceName: service-nodejs-productos
          servicePort: 5000
      - path: /api/productos
        backend:
          serviceName: service-nodejs-productos
          servicePort: 5000
      - path: /api/proveedores
        backend:
          serviceName: service-nodejs-proveedores
          servicePort: 5000
      - path: /api/reportes
        backend:
          serviceName: service-nodejs-reportes
          servicePort: 5000
  tls:
  - secretName: joomla-tls-cert
    hosts:
      - poliformas.com.gt
      - backend.poliformas.com.gt