apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-nodejs-movimientos
spec:
  selector:
    matchLabels:
      app: nodejs-movimientos
  template:
    metadata:
      labels:
        app: nodejs-movimientos
    spec:
      containers:
      - name: nodejs-container
        image: christianreal/backend-nodejs:test2-movimientos
        envFrom:
          - secretRef:
              name: secretos-proyecto
        ports:
        - containerPort: 5000
        imagePullPolicy: Always