apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-nodejs-reportes
spec:
  selector:
    matchLabels:
      app: nodejs-reportes
  template:
    metadata:
      labels:
        app: nodejs-reportes
    spec:
      containers:
      - name: nodejs-container
        image: christianreal/backend-nodejs:test2-reportes
        envFrom:
          - secretRef:
              name: secretos-proyecto
        ports:
        - containerPort: 5000
        imagePullPolicy: Always