apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-nodejs-proveedores
spec:
  selector:
    matchLabels:
      app: nodejs-proveedores
  template:
    metadata:
      labels:
        app: nodejs-proveedores
    spec:
      containers:
      - name: nodejs-container
        image: christianreal/backend-nodejs:test2-proveedores
        envFrom:
          - secretRef:
              name: secretos-proyecto        
        ports:
        - containerPort: 5000
        imagePullPolicy: Always