apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-nodejs
spec:
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: nodejs-container
        image: christianreal/backend-nodejs:test2
        env:
        - name: "DB_USER"
          valueFrom:
            secretKeyRef:
              name: credenciales-db
              key: DB_USER
        - name: "DB_PASS"
          valueFrom:
            secretKeyRef:
              name: credenciales-db
              key: DB_PASS
        - name: "DB_DATABASE"
          valueFrom:
            configMapKeyRef:
              name: config-db
              key: DB_DATABASE
        - name: "DB_HOST"
          valueFrom:
            configMapKeyRef:
              name: config-db
              key: DB_HOST
        ports:
        - containerPort: 5000