apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-vuejs
spec:
  selector:
    matchLabels:
      app: vuejs
  template:
    metadata:
      labels:
        app: vuejs
    spec:
      containers:
      - name: vuejs-container
        image: christianreal/frontend-vuejs
        ports:
        - containerPort: 80