apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-nodejs-vendedores
spec:
  selector:
    matchLabels:
      app: nodejs-vendedores
  template:
    metadata:
      labels:
        app: nodejs-vendedores
    spec:
      containers:
      - name: nodejs-container
        image: christianreal/backend-nodejs:test2-vendedores
        envFrom:
          - secretRef:
              name: secretos-proyecto
        ports:
        - containerPort: 5000
        imagePullPolicy: Always